### ISSUE TITLE
Whos on the team?? 

### ISSUE THREAD

**Issue by i-marsh** [save-the-universe/earth#2]
It's not clear who the team is ... do we have a recruitment process.. 
recommend we go after

- [x] Thor
- [x] SpiderMan
- [x] ~~Wonder Woman~~
- [x] SuperTed 

@d34d-p00l  what dya think 😸

**Comment by d34d-p00l** [comment]
So we can't do WW she's DC
and who's superted ??? !!! 🐻 @i-marsh

**Comment by i-marsh** [comment]
you dnt know st.. 

ok updating list
![image](https://user-images.githubusercontent.com/35036892/40137866-7111bd4a-5919-11e8-93f0-329006680667.png)
